# Video Transcoding Resource Prediction model

A simple deep learning neural network that allows to predict needed resources for a certain resolution and latency. 


## Implementation
The implementation of this initial model is using the Multiple Output Regression, where the input data are the resoluion *r* and the wanted latency *l*. The output are the max_cpu, max_memory, throughput and storage.

### Note 
For initial implementation we will generate a random data and build a simple model as our aim is not to make the model but to showcase the architecture.


In [2]:
# Importing make_regression function to generate sample data 
from sklearn.datasets import make_regression
# Importing numpy to manage datasets 
import numpy as np
# Importing keras to create neural networks model
from keras.models import Sequential
from keras.layers import Dense

In [2]:
# The make_regression function creates a random regression problem dataset
x, y = make_regression(n_samples=1000, n_features=2, n_informative=2, n_targets=4, random_state=5)
# X is the input dataset 
# y is the output dataset 
x = np.absolute(x)
y = np.absolute(y)

# rounding values to int 
x = np.rint(x)
y = np.rint(y)
print(x)
print(y)

print(x.shape, y.shape)

[[2. 0.]
 [2. 1.]
 [1. 0.]
 ...
 [1. 0.]
 [0. 2.]
 [0. 1.]]
[[139.  86. 100.  78.]
 [152.  91. 108.  85.]
 [ 53.  34.  39.  30.]
 ...
 [ 41.  45.  40.  20.]
 [196.  15.  84. 123.]
 [ 85.  14.  40.  53.]]
(1000, 2) (1000, 4)


In [3]:
# create a simple neural network
model = Sequential()
# adding a hidden layer 
# setting the kernel initializer to be uniform to initialize weights
model.add(Dense(10, input_dim=2, kernel_initializer='he_uniform', activation='relu'))
# adding an output layer 
model.add(Dense(4))
model.compile(loss='mae', optimizer='adam')

2022-05-27 20:36:41.100977: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-05-27 20:36:41.101123: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (kero): /proc/driver/nvidia/version does not exist
2022-05-27 20:36:41.105301: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


(1000, 10) (1000, 3)
